
printf("\n// Autogenerated\n")
printf("// 'ruby ./ako-tables.rb > ./ako-tables.h'\n")
printf("#include <stdint.h>\n")

####

MAX_VALUES = 16

i = 0
x = 2

printf("\n#define VALID_DIMENSIONS_NO #{MAX_VALUES}\n")
print("static const size_t s_valid_dimensions[VALID_DIMENSIONS_NO] = {\n")

while i < MAX_VALUES do
	print("\t#{x},\n")
	x = x * 2
	i = i + 1
end

printf("};\n")
